language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
before_script:
  - wget -nv https://commondatastorage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.2.zip
  - unzip -q google_appengine_1.9.2.zip
script:
  - ./run_tests.py

